<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class cargos_seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cargos')->insert([
            ['cargo' => 'Sin Cargo'],
            ['cargo' => 'COORDINADOR'],
            ['cargo' => 'CONSULTOR JURIDICO'],
            ['cargo' => 'GERENTE'],
            ['cargo' => 'GERENTE GENERAL'],
            ['cargo' => 'JEFE DE DIVISIÓN'],
            ['cargo' => 'ANALISTA TÉCNICO'],
            ['cargo' => 'JEFE DE DIVISION PROVISIONAL'],
            ['cargo' => 'ASISTENTE ADMINISTRATIVO'],
            ['cargo' => 'ASISTENTE TÉCNICO'],
            ['cargo' => 'AUXILIAR TÉCNICO'],
            ['cargo' => 'CAJERO'],
            ['cargo' => 'PROYECTISTA'],
            ['cargo' => 'PROMOTOR COMUNITARIO'],
            ['cargo' => 'LABORATORISTA'],
            ['cargo' => 'AUDITOR INTERNO ENCARGADO'],
            ['cargo' => 'COORDINADOR SUPLENTE'],
            ['cargo' => 'INSPECTOR DE OBRAS'],
            ['cargo' => 'ABOGADO'],
            ['cargo' => 'ANALISTA ADMINISTRATIVO'],
            ['cargo' => 'ASEADOR'],
            ['cargo' => 'AUDITOR'],
            ['cargo' => 'AYUDANTE DE LABORATORIO'],
            ['cargo' => 'CHOFER'],
            ['cargo' => 'DIBUJANTE'],
            ['cargo' => 'ESPECIALISTA'],
            ['cargo' => 'INSPECTOR TÉCNICO'],
            ['cargo' => 'JARDINERO'],
            ['cargo' => 'LECTOR NOTIFICADOR'],
            ['cargo' => 'MENSAJERO'],
            ['cargo' => 'OPERADOR DE ESTACIÓN DE BOMBEO'],
            ['cargo' => 'OPERADOR DE ACUEDUCTOS MENORES'],
            ['cargo' => 'PLANIFICADOR'],
            ['cargo' => 'RECEPCIONISTA'],
            ['cargo' => 'AUXILIAR DE PLANTA'],
            ['cargo' => 'GUARDIA DE SEGURIDAD'],
            ['cargo' => 'AUXILIAR DE ENFERMERIA / ENFERMERA '],
            ['cargo' => 'DISEÑADOR GRÁFICO Y PUBLICISTA'],
            ['cargo' => 'ESTADISTICO'],
            ['cargo' => 'OPERADOR DE MAQUINARIA PESADA'],
            ['cargo' => 'TOPÓGRAFO'],
            ['cargo' => 'INSPECTOR TECNICO DE SEGURIDAD INDUSTRIAL '],
            ['cargo' => 'AUXILIAR TECNICO'],
            ['cargo' => 'COMUNICADOR SOCIAL'],
            ['cargo' => 'AUXILIAR DE DIQUE'],
            ['cargo' => 'GUARDADIQUE'],
            ['cargo' => 'GUARDIAS DE SEGURIDAD'],
            ['cargo' => 'ASISTENTE TECNICO'],
            ['cargo' => 'INSPECTOR DE SEGURIDAD INDUSTRIAL'],
            ['cargo' => 'ANALISTA DE CAMPO'],
            ['cargo' => 'ANALISTA DE  COBRANZA'],
            ['cargo' => 'ANÁLISTA DE  FACTURACIÓN'],
            ['cargo' => 'ANALISTA DE  TESORERIA'],
            ['cargo' => 'ASISTENTE DE INGENIERO'],
            ['cargo' => 'INGENIERO DE CAMPO,  ASESOR'],
            ['cargo' => 'INSPECTOR TÉCNICO  MANTENIMIENTO'],
            ['cargo' => 'JEFE DE DEPARTAMENTO'],
            ['cargo' => 'JEFE DE UNIDAD'],
            ['cargo' => 'SUBGERENTE'],
            ['cargo' => 'TÉCNICO DE PLANTA'],
            ['cargo' => 'ELECTROMECANICO'],
            ['cargo' => 'GERENTE GENERAL ADMINISTRATIVO'],
            ['cargo' => 'GERENTE GENERAL TECNICO'],
            ['cargo' => 'GERENTE GENERAL DE OPERACIONES'],
            ['cargo' => 'GERENTE GENERAL DE OPERACIONES PROVISIONAL'],
            ['cargo' => 'GERENTE PROVISIONAL'],
            ['cargo' => 'AUDITOR INTERNO  ENCARGADO'],
            ['cargo' => 'GERENTE GENERAL COMERCIAL PROVISIONAL'],
            ['cargo' => 'OPERADOR DE ESTACION DE BOMBEO'],
            ['cargo' => 'PRESIDENTE'],
            ['cargo' => 'INSPECTOR TECNICO'],
            ['cargo' => 'INSPECTOR'],
            ['cargo' => 'ESPECIALISTA TECNICO'],
            ['cargo' => 'DISENADOR GRAFICO Y PUBLICISTA'],
            ['cargo' => 'TECNICO DE PLANTA'],
            ['cargo' => 'ANALISTA DE FACTURACION'],
            ['cargo' => 'ANALISTA DE COBRANZA'],
            ['cargo' => 'ANALISTA DE TESORERIA'],
            ['cargo' => 'ASISTENTE DE INGENIEROS'],
            ['cargo' => 'ANALISTA DE ADMINISTRACION'],
            ['cargo' => 'ING DE CAMPO ASESOR'],
        ]);
    }
}
